### ISSUE TITLE
リソース設計

### ISSUE THREAD

**Issue by junohm410** [junohm410/fjord-flea-market#19]
## レビューOKを頂いた提出内容

| Method | Path                                      | Description                                    |
|--------|-------------------------------------------|------------------------------------------------|
| GET    | /                                  | ログイン前TOPページを表示                            |
| GET    | /items                                    | 購入希望を出せる商品の一覧を表示                            |
| GET    | /items/:item_id                           | 商品の詳細を表示                            |
| GET    | /items/new                                | 新しい商品の登録フォームを表示            |
| POST   | /items                                    | 新しい商品の保存                            |
| GET    | /items/:item_id/edit                      | 商品の編集するフォームを表示                 |
| PUT    | /items/:item_id                           | 商品の更新                                  |
| DELETE | /items/:item_id                           | 商品を削除                                  |
| POST   | /items/:item_id/purchase_requests         | 商品に対して購入希望を出す                   |
| DELETE | /items/:item_id/purchase_requests/:purchase_request_id     | 購入希望を削除                                  |
| POST   | /items/:item_id/comments                  | 商品に対してコメントを作成                  |
| PUT    | /items/:item_id/comments/:comment_id      | コメントを更新                                  |
| DELETE | /items/:item_id/comments/:comment_id      | コメントを削除                                  |
| GET    | /listed_items                       | ログインユーザーによる商品一覧を表示          |
| GET    | /requested_items             | ログインユーザーが購入希望を出した商品一覧を表示 |
| GET    | /terms                                    | 利用規約・プライバシーポリシーを表示する         |
| GET    | /withdraw                           | 退会ページを表示する                            |
| DELETE | /users/:user_id                                | ユーザー情報を削除する（退会）                  |
| GET    | /notifications                            | 通知の一覧を表示                                |
| GET    | /notifications/:notification_id           | 通知を既読にして、通知対象の商品ページにリダイレクトする                                |
| POST   | /users/auth/discord                       | ログインする                                    |
| DELETE | /logout                                   | ログアウトする                                  |

<details>
<summary>一回目の提出</summary>
- エレベーターピッチ: https://bootcamp.fjord.jp/products/18374
- ペーパープロトタイプ: https://bootcamp.fjord.jp/products/19496 

| Method | Path                                      | Description                                    |
|--------|-------------------------------------------|------------------------------------------------|
| GET    | /                                  | ログイン前TOPページを表示                            |
| GET    | /items                                    | 購入希望を出せる商品の一覧を表示                            |
| GET    | /items/:item_id                           | 商品の詳細を表示                            |
| GET    | /items/new                                | 新しい商品の登録フォームを表示            |
| POST   | /items                                    | 新しい商品の保存                            |
| GET    | /items/:item_id/edit                      | 商品の編集するフォームを表示                 |
| PUT    | /items/:item_id                           | 商品の更新                                  |
| DELETE | /items/:item_id                           | 商品を削除                                  |
| POST   | /items/:item_id/purchase_requests         | 商品に対して購入希望を出す                   |
| DELETE | /items/:item_id/purchase_requests/:purchase_request_id     | 購入希望を削除                                  |
| POST   | /items/:item_id/comments                  | 商品に対してコメントを作成                  |
| PUT    | /items/:item_id/comments/:comment_id      | コメントを更新                                  |
| DELETE | /items/:item_id/comments/:comment_id      | コメントを削除                                  |
| GET    | /current_user/items                       | ログインユーザーによる商品一覧を表示          |
| GET    | /current_user/requested_items             | ログインユーザーが購入希望を出した商品一覧を表示 |
| GET    | /terms                                    | 利用規約・プライバシーポリシーを表示する         |
| GET    | /delete_account                           | 退会ページを表示する                            |
| DELETE | /users/:user_id                                | ユーザー情報を削除する（退会）                  |
| GET    | /notifications                            | 通知の一覧を表示                                |
| GET    | /notifications/:notification_id           | 通知を既読にして、通知対象の商品ページにリダイレクトする                                |
| POST   | /users/auth/discord                       | ログインする                                    |
| DELETE | /logout                                   | ログアウトする                                  |

### 補足
- ログイン機能（Discord認証）
  - `omniauth-discord` gem + `devise` gem の構成で実装予定です
- コメント関連
  - 商品に紐づくコメント一覧は商品ページに表示されるので、 `GET /items/:item_id/comments` と `GET /items/:item_id/comments/:comment_id`は無し
  - 新規追加フォームも商品ページに常にあるので、そのためのPathも無し
  - 既存のコメントの編集フォームは、Hotwireでコメント本文がフォームになるように実装するつもりなので、そのためのPathも無し
- 通知一覧を見るページはペーパープロトタイプに載っておらず、またこれ自体が必要になるかわからない（ログイン後TOPの上部にリストで表示されるくらいでもいい？作ってデモして決める）という感じなのですが、現段階ではリソースとして用意しました
</details>

**Comment by kaito0046** [comment]
> GET 	/current_user/items 	ログインユーザーによる商品一覧を表示
> GET 	/current_user/requested_items 	ログインユーザーが購入希望を出した商品一覧を表示

current_user という文字列がリソースにつくのがちょっと違和感ありました。特に「特定のユーザー」を明示しない文脈では、リソースは操作者に関連づくものと考える習慣がついているからかもしれません。
current_user という語は使わずに、`/{出品中の商品一覧}` `/requested_items` というパスで十分操作者のものだとわかりますし、シンプルで自然にできそうな気がします（他のユーザーの出品中商品一覧や購入希望商品の一覧ページもあるならまた話は変わってきますが）。

**Comment by kaito0046** [comment]
> GET 	/delete_account 	退会ページを表示する

withdraw という語が使われているのをわりとよく見る気がします。
ただ、現状でもおかしくはないので、お好みでよいと思います〜

**Comment by kaito0046** [comment]
それ以外はよさそうです！

**Comment by junohm410** [comment]
@kaito0046 

ご確認、ありがとうございました🙏

## ログインユーザーによる商品一覧を表示 /  ログインユーザーが購入希望を出した商品一覧を表示
ご指摘いただきましたとおり、他のユーザーの出品中商品一覧ページなどは作らない（コンセプト的にもユーザーごとにお店を持つショッピングモール的なアプリではない）ので、current_userの持ち物であることはリソースになくても自明だと思いました🙏

自分の出品の商品一覧については、`listed_items`と表現したいと思います。
（listには「〜を出品する」という意味があり、その過去分詞 + itemsで「出品された商品」）

## 退会ページの表示
また、退会ページについてのアドバイスもありがとうございます🙏
実はしっくり来るものが思い浮かず悩んでいたので（事前に書けばよかったですね🙇‍♂️）、withdrawを使いたいと思います。

## 修正
修正部分のみお伝えしたほうが見やすいかなと思いましたので、下に書きます。
再度ご確認のほどよろしくお願いします🙏
（最終形はレビュー後にまとめ直して貼っておくつもりです）

| Method | Path                                      | Description                                    |
|--------|-------------------------------------------|------------------------------------------------|
| GET    | /listed_items                       | ログインユーザーによる商品一覧を表示          |
| GET    | /requested_items             | ログインユーザーが購入希望を出した商品一覧を表示 |
|GET  |/withdraw  | 退会ページを表示する  |

**Comment by kaito0046** [comment]
よさそうです〜！

**Comment by junohm410** [comment]
@kaito0046 
ご確認、ありがとうございました！🙏
