### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by junohm410** [junohm410/fjord-flea-market#20]
- エレベーターピッチ: https://bootcamp.fjord.jp/products/18374
- ペーパープロトタイプ: https://bootcamp.fjord.jp/products/19496 

```mermaid
erDiagram
    Users {
        integer id PK
        string name
        integer uid
        string avatar_url
        string provider
        datetime created_at
        datetime updated_at
    }

    Items {
        integer id PK
        string name
        text description
        integer price
        boolean shipping_cost_covered
        string payment_method
        datetime deadline
        integer status
        integer user_id FK
        integer buyer_id FK
        datetime created_at
        datetime updated_at
    }

    PurchaseRequests {
        integer id PK
        integer user_id FK
        integer item_id FK
        datetime created_at
        datetime updated_at
    }

   Notifications {
        integer id PK
        string message
        string target_link
        boolean read
        integer receiver_id FK
        datetime created_at
        datetime updated_at
    }                 

    Comments {
        integer id PK
        string content
        integer item_id FK
        integer user_id FK
        datetime created_at
        datetime updated_at
    }

    Users ||--o{ Items : ""
    Users |o--o{ Items : "buyer_id"
    Users ||--o{ PurchaseRequests : ""
    Users ||--o{ Notifications : "receiver_id"
    Users ||--o{ Comments : ""

    Items ||--o{ PurchaseRequests : ""
    Items ||--o{ Comments : ""
```

※商品画像のアップロード機能はActiveStorageで実装する予定です。上記のテーブル以外にActiveStorageが自動で作るテーブルも存在する認識ですが、割愛しています。

### Users
ログイン機能は Discord認証（omniauth-discord gem） + devise gem で実装予定です。
`uid`, `provider`はそのoauth用のカラムになります。
また、`avatar_url`はDiscord認証で取れるアイコン画像のurlの文字列です。

### Items
`shipping_cost_covered`は出品者が送料を持つ / 持たないを表す`boolean`が入ります。
`deadline`が購入期限を出せる締め切り日で、この日が過ぎると自動的に購入者を抽選で確定します。
Rakeタスクで抽選作業を行い、購入者になったユーザーの`id`が`buyer_id`に入ります。

`status`は商品の状態を表すカラムで、`enum`を使おうと思っています。
イメージですが、下のような形で 非公開 / 出品中 / 購入者確定 を表現したいと思っています。
```rb
enum status: { unpublished: 0, listing: 1, buyer_chosen: 2 }
```

#### 悩んだこと: 「商品」と「出品」をテーブルで分けるか
今はItemsが実質「出品」を表しています（`item  -> purchase_request <-  user`な結びつき）。

これを、`item -> 出品 -> purchase_request <-  user`というふうに、出品を別テーブルに分けることもできそうと感じました。
そうすると、「登録してある在庫商品から出品するものを選ぶ」というようなコンセプトになるかなというイメージです。

※分けない場合、`status`が`unpublished`（非公開状態）であれば在庫があるけれど出品していない状態になり、もし期限中に誰も購入者がつかなかった場合は自動的に`unpublished`になり在庫に戻る、というような流れにする

他のサービスの例としてメルカリを見てみると、ユーザーが作るのは「（出品の要素を持った）商品」という感じで、出品を別テーブルにはしていないように見えました。
- ユーザーが商品をサブミットしたあとの出品ページのurl -> `/item/{id}`
    - 出品を一時取り下げて、その後再出品しても、その商品を見るためのurlは変わらない（取り下げ中は自分にしか見えない）

出品と商品を分けると柔軟性が増すようにも思えたのですが、

- 商品を作ってから関連する出品を作る、という流れになるのがユーザーフレンドリーじゃない気がする
- 「商品だけ更新する」「出品だけ更新する」という流れもできると思うが、これができる事自体がユーザーを悩ませそう
- 「出品して購入者を決めてもらう」というところにフォーカスしたシンプルなアプリにするのであれば、そこまでの複雑性は不要な気がする

という考えから、最終的に上に示した出品を分けないDB設計案で行こうと考えました。

### Notifications
以下のような通知を扱うためのテーブルです。
- 「購入者が決まりました」 to 出品者
- 「商品が更新されました」 to 購入希望者

通知の送信者を誰（何）にするか悩みましたが、送信者は「アプリ」と考え、カラムでは持たせていません。
受取者と、Webアプリ上でその通知をクリックした際に遷移する商品ページへのリンクのカラムを持たせる意図で設計しています。

（`notifiable_type`と`notifiable_id`というカラムを持たせて、商品やコメントとポリモーフィック関連にするような実装も考えましたが、「ある特定の商品に基づいた通知だけを`item.notifications`でソートする」というようなことは実際はなさそうだと思ったのと、ターゲットのリンクをもたせるだけの実装のほうがシンプルかつ十分に感じたので、このような方針を考えました）

`read`は未読 / 既読を表す`boolean`です。

**Comment by kaito0046** [comment]
良さそうに思います！
設計の背景が詳しく書かれていてわかりやすいです。
WHYはホント意識して残さないと「コレなんでこうしたんだっけ？」となりがちで（実際の開発現場でも）、未来の誰かが困ることになります。なのでこの習慣はぜひ続けていただきたいです〜 👍

**Comment by junohm410** [comment]
@kaito0046 
ご確認、ありがとうございました🙏

> WHYはホント意識して残さないと「コレなんでこうしたんだっけ？」となりがちで（実際の開発現場でも）、未来の誰かが困ることになります。なのでこの習慣はぜひ続けていただきたいです〜 👍

ありがとうございます。プルリクにおけるWHYもそうですが設計のWHYも大事かなと感じたので、そのあたりが上手くできていたのであればよかったです！今後も続けたいと思います🙏

---

一点だけ質問というか、感覚をお伺いしたいイメージなのですが、

> 悩んだこと: 「商品」と「出品」をテーブルで分けるか

> これを、item -> 出品 -> purchase_request <-  userというふうに、出品を別テーブルに分けることもできそうと感じました。
そうすると、「登録してある在庫商品から出品するものを選ぶ」というようなコンセプトになるかなというイメージです。

このあたりについては、『↑のような設計もあるしその利点もあるけれど、shodanがそうしなかったWHYにも理があるし、現在の「出品」を「商品」と分けない設計でも筋は通っているのでOK』、くらいのイメージということであっていますでしょうか？

設計に絶対の正解はないとは思うのですが、この設計部分については悩んだところだったので、kaitoさんのご感想をもらえるとありがたいな、くらいの気持ちです🙇‍♂️

お手数ですが、ご確認の程よろしくお願いいたします🙏

**Comment by kaito0046** [comment]
> このあたりについては、『↑のような設計もあるしその利点もあるけれど、shodanがそうしなかったWHYにも理があるし、現在の「出品」を「商品」と分けない設計でも筋は通っているのでOK』、くらいのイメージということであっていますでしょうか？

現状の設計でやりたいことは十分満たせてますし、シンプルな現状の方がベターだろうな、という感じに思っていました！
出品と商品を分けた方がよさそうなのは、おっしゃるとおり商品をあらかじめ登録しておきたい場合や、一つの出品に商品を複数紐づけたい場合などが該当するかなと思います（そんなユースケースが現実に存在するかはわかりませんが）。
今回やりたいことはそこまで複雑ではないので、シンプルな方に倒されていてgoodだと思っていました〜

**Comment by junohm410** [comment]
@kaito0046 
コメント頂きありがとうございます！🙏
大変クリアになりました。

> 一つの出品に商品を複数紐づけたい場合などが該当するかなと思います

確かに、こういうのはあるなと思いました👀
テーブルを分けることで実現できることの例として、引き出しが増えたような感覚です（実際にそういうことをするかはともかくですが）。
こちらもシェアいただき、ありがとうございます。

> 今回やりたいことはそこまで複雑ではないので、シンプルな方に倒されていてgoodだと思っていました〜

シンプルに行こうときめつつこれでいいか不安、というのが正直なところだったので、そういっていただけて安心しました😄
引き続き頑張りたいと思います！レビューありがとうございました🙏
